skyportal/gwemopt

ToO/ToO_manager.py

sarrah's upgrade of the ToO_manager.py

update of the ToO_manager.py

---

gwemopt/utils.py
setup.py

Fixing #18 by using the `ligo.skymap.dist.ud_grade()` function instead of the healpy one.

changing the ud_grade method

---

gwemopt/catalog.py

@mcoughlin , you last change work well but you added a new normalization on the selected tiles. Of courses this change the outputed grades on the galaxies. So I don't think we want this new nnormalization here.

commenting the normalization

---

gwemopt/coverage.py
gwemopt/hungarian.py
gwemopt/scheduler.py

Please review changes once if possible to make sure I didn't overwrite any of your changes.  Let me know if I need to fix anything. Thanks!

Adding airmass and observation time to xml and dat file outputs

---

bin/gwemopt_run
gwemopt/catalog.py

The grade associated to galaxies can be changed through the galaxy_grade option. It can be either 'S' or 'Sloc'. Feel free to change the names if you find better ones.
In order to keep track of the galaxy identifiers, I added them in the ouptut file for the GLADE catalog.
I removed the "if params["doPlots"]:" condition, previously used to save the top 1000 galaxies in a csv file, as we do want this file even if we do not ask for plots. If you prefer to have a condition, I can add one.
I have made some changes to respect the pep8 format as much as possible.

Added choice of galaxy grade to use

---

config/Lisnyky-AZT8.config

Request from @santier14 to add new ukrainien telescope config file.

adding new telescope config file

---

config/ShAO-T60.config

Add a new telescope config file and tessellation (again) as requested by @santier14 .
@mcoughlin

add new telescope

---

config/ShAO-T60.config
gwemopt/catalog.py

As we discussed during LVC meeting i changed here the way galaxies are cutted.
We do consider only the galaxies inside 3 sigma error in distance.
I tested the results, seems ok.
I did the python setup.py test --addopts="-xvv"
@mcoughlin

Changing galaxy cut

---

config/DECam.config
config/GIT.config
config/Gattini.config
config/KPED.config
config/ZTF.config
gwemopt/scheduler.py
gwemopt/utils.py
setup.py

For some reason all my commits are showing up in here....
- improved runtime for Hungarian algorithm
- added munkres to setup.py requirement
- updated mjd from mid to start mjd
- add overheads for each telescope

Add overheads

---

gwemopt/catalog.py
gwemopt/tiles.py
gwemopt/utils.py

Changing the condition checking in case overhead_per_exposure is not in the config file.
@mcoughlin

changing the if condition security for overhead_per_exposure

---

gwemopt/catalog.py

This change aims at exporting only galaxies whose distance is compatible within 3 sigma distance  in the output file.

exporting only galaxies whose distance is compatible within 3 sigma distance

---

gwemopt/coverage.py
gwemopt/utils.py

- block completion seems to work; please test
- added 30 min between consecutive blocks
- added filter change time to overheads for integrated schedule

Fix filterschedule

---

bin/gwemopt_run
gwemopt/catalog.py

I added the use of a new grade using the galaxies stellar masses.
The new grade can be used using --galaxy_grade=Smass. It required to download the mangrove catalog form https://mangrove.lal.in2p3.fr, done automatically by the code.

Adding the new grade using stellar mass

---

gwemopt/coverage.py

Since I changed the output of the my scheduler since last time, coverage.py had to be updated to work with it again. That is what I did here.

Coverage update

---

gwemopt/samplers.py

Include attribute assignment in loop over tile IDs. Some extra lines are included here that I didn't change but they seem to be just white space... Not sure what happened there.

Added one indent to lines 252-257 of samplers.py

---

config/TELESTO.config

I added the TELESTO.config file. Please review and let me know.

Added the config file for TELESTO

---

gwemopt/skyportal.py

Allow to slice out only relevant fields

Allow to slice out only relevant fields

---

gwemopt/coverage.py
gwemopt/utils.py

More numpy fixing 

---

gwemopt/params.py
setup.py

Specify package data

---

gwemopt/__main__.py
gwemopt/tests/test_schedule.py
gwemopt/utils/skymap.py
gwemopt/utils/tile_utils.py

Extract gpstime/is3D from skymap itself

---

gwemopt/args.py
gwemopt/run.py
gwemopt/utils/skymap.py
pyproject.toml

Set default output directory

---

gwemopt/utils/misc.py

This PR makes filt_change_time optional.

filt_change_time

---

gwemopt/args.py
gwemopt/catalogs/get.py
gwemopt/params.py

This PR makes the number of galaxies configurable.

Number of galaxies configurable

---

gwemopt/io/skymap.py

This PR allows for map_struct to be passed directly.

map_struct

---

.github/workflows/continous_integration.yml
gwemopt/io/skymap.py
gwemopt/tests/test_gracedb.py
pyproject.toml

This PR bumps minimum version to 3.9.

python >= 3.9
